package com.maxot.seekandcatch.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// === Pixel Light Colors ===

val primaryLight = Color(0xFFD6D68D)
val onPrimaryLight = Color(0xFF1A3B20)
val primaryContainerLight = Color(0xFFE8E8AA)
val onPrimaryContainerLight = Color(0xFF1A3B20)

val secondaryLight = Color(0xFF2E5B3D)
val onSecondaryLight = Color(0xFFD6D68D)
val secondaryContainerLight = Color(0xFF3D6D50)
val onSecondaryContainerLight = Color(0xFFD6D68D)

val tertiaryLight = Color(0xFF6D5676)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF6D9FF)
val onTertiaryContainerLight = Color(0xFF271430)

val errorLight = Color(0xFF9B2A2A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFB45555)
val onErrorContainerLight = Color(0xFFF8E2E2)

val backgroundLight = Color(0xFF1A3B20)
val onBackgroundLight = Color(0xFFD6D68D)

val surfaceLight = Color(0xFF254D30)
val onSurfaceLight = Color(0xFFD6D68D)

val surfaceVariantLight = Color(0xFF2E5B3D)
val onSurfaceVariantLight = Color(0xFFD6D68D)

val outlineLight = Color(0xFFD6D68D)
val outlineVariantLight = Color(0xFFBEBE9F)

val scrimLight = Color(0xFF000000)

val inverseSurfaceLight = Color(0xFFE8E8AA)
val inverseOnSurfaceLight = Color(0xFF1A3B20)
val inversePrimaryLight = Color(0xFFB4BB74)

val surfaceDimLight = Color(0xFF1A3B20)
val surfaceBrightLight = Color(0xFF3A6A40)
val surfaceContainerLowestLight = Color(0xFF1A3B20)
val surfaceContainerLowLight = Color(0xFF224F31)
val surfaceContainerLight = Color(0xFF254D30)
val surfaceContainerHighLight = Color(0xFF2E5B3D)
val surfaceContainerHighestLight = Color(0xFF3D6D50)

//val primaryLightMediumContrast = Color(0xFF1C4472)
//val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
//val primaryContainerLightMediumContrast = Color(0xFF5376A7)
//val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
//val secondaryLightMediumContrast = Color(0xFF394354)
//val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
//val secondaryContainerLightMediumContrast = Color(0xFF6A7587)
//val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
//val tertiaryLightMediumContrast = Color(0xFF503B5A)
//val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
//val tertiaryContainerLightMediumContrast = Color(0xFF846C8E)
//val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
//val errorLightMediumContrast = Color(0xFF8C0009)
//val onErrorLightMediumContrast = Color(0xFFFFFFFF)
//val errorContainerLightMediumContrast = Color(0xFFDA342E)
//val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
//val backgroundLightMediumContrast = Color(0xFFF9F9FF)
//val onBackgroundLightMediumContrast = Color(0xFF191C20)
//val surfaceLightMediumContrast = Color(0xFFF9F9FF)
//val onSurfaceLightMediumContrast = Color(0xFF191C20)
//val surfaceVariantLightMediumContrast = Color(0xFFE0E2EB)
//val onSurfaceVariantLightMediumContrast = Color(0xFF3F434A)
//val outlineLightMediumContrast = Color(0xFF5B5F67)
//val outlineVariantLightMediumContrast = Color(0xFF777B83)
//val scrimLightMediumContrast = Color(0xFF000000)
//val inverseSurfaceLightMediumContrast = Color(0xFF2E3035)
//val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F0F7)
//val inversePrimaryLightMediumContrast = Color(0xFFA5C8FE)
//val surfaceDimLightMediumContrast = Color(0xFFD9DAE0)
//val surfaceBrightLightMediumContrast = Color(0xFFF9F9FF)
//val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
//val surfaceContainerLowLightMediumContrast = Color(0xFFF2F3FA)
//val surfaceContainerLightMediumContrast = Color(0xFFEDEDF4)
//val surfaceContainerHighLightMediumContrast = Color(0xFFE7E8EE)
//val surfaceContainerHighestLightMediumContrast = Color(0xFFE1E2E9)
//
//val primaryLightHighContrast = Color(0xFF002345)
//val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
//val primaryContainerLightHighContrast = Color(0xFF1C4472)
//val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
//val secondaryLightHighContrast = Color(0xFF182332)
//val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
//val secondaryContainerLightHighContrast = Color(0xFF394354)
//val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
//val tertiaryLightHighContrast = Color(0xFF2E1A37)
//val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
//val tertiaryContainerLightHighContrast = Color(0xFF503B5A)
//val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
//val errorLightHighContrast = Color(0xFF4E0002)
//val onErrorLightHighContrast = Color(0xFFFFFFFF)
//val errorContainerLightHighContrast = Color(0xFF8C0009)
//val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
//val backgroundLightHighContrast = Color(0xFFF9F9FF)
//val onBackgroundLightHighContrast = Color(0xFF191C20)
//val surfaceLightHighContrast = Color(0xFFF9F9FF)
//val onSurfaceLightHighContrast = Color(0xFF000000)
//val surfaceVariantLightHighContrast = Color(0xFFE0E2EB)
//val onSurfaceVariantLightHighContrast = Color(0xFF20242B)
//val outlineLightHighContrast = Color(0xFF3F434A)
//val outlineVariantLightHighContrast = Color(0xFF3F434A)
//val scrimLightHighContrast = Color(0xFF000000)
//val inverseSurfaceLightHighContrast = Color(0xFF2E3035)
//val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
//val inversePrimaryLightHighContrast = Color(0xFFE3ECFF)
//val surfaceDimLightHighContrast = Color(0xFFD9DAE0)
//val surfaceBrightLightHighContrast = Color(0xFFF9F9FF)
//val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
//val surfaceContainerLowLightHighContrast = Color(0xFFF2F3FA)
//val surfaceContainerLightHighContrast = Color(0xFFEDEDF4)
//val surfaceContainerHighLightHighContrast = Color(0xFFE7E8EE)
//val surfaceContainerHighestLightHighContrast = Color(0xFFE1E2E9)

val primaryDark = Color(0xFFD6D68D)                // Жовта рамка / кнопки
val onPrimaryDark = Color(0xFF1A3B20)              // Темно-зелений текст
val primaryContainerDark = Color(0xFFBEBE7A)
val onPrimaryContainerDark = Color(0xFF1A3B20)

val secondaryDark = Color(0xFF3D6D50)              // Зелений для елементів
val onSecondaryDark = Color(0xFFD6D68D)
val secondaryContainerDark = Color(0xFF2E5B3D)
val onSecondaryContainerDark = Color(0xFFD6D68D)

val tertiaryDark = Color(0xFF6D5676)
val onTertiaryDark = Color(0xFFFFFFFF)
val tertiaryContainerDark = Color(0xFF3D2946)
val onTertiaryContainerDark = Color(0xFFF6D9FF)

val errorDark = Color(0xFF9B2A2A)
val onErrorDark = Color(0xFFFFFFFF)
val errorContainerDark = Color(0xFF5D1A1A)
val onErrorContainerDark = Color(0xFFF8E2E2)

val backgroundDark = Color(0xFF0E1A13)             // Дуже темно-зелений фон
val onBackgroundDark = Color(0xFFD6D68D)

val surfaceDark = Color(0xFF1A3B20)                // Фон діалогів
val onSurfaceDark = Color(0xFFD6D68D)

val surfaceVariantDark = Color(0xFF224F31)
val onSurfaceVariantDark = Color(0xFFD6D68D)

val outlineDark = Color(0xFFD6D68D)
val outlineVariantDark = Color(0xFFBEBE9F)

val scrimDark = Color(0xFF000000)

val inverseSurfaceDark = Color(0xFFE8E8AA)
val inverseOnSurfaceDark = Color(0xFF1A3B20)
val inversePrimaryDark = Color(0xFFB4BB74)

val surfaceDimDark = Color(0xFF0E1A13)
val surfaceBrightDark = Color(0xFF2E5B3D)

val surfaceContainerLowestDark = Color(0xFF0C120F)
val surfaceContainerLowDark = Color(0xFF142820)
val surfaceContainerDark = Color(0xFF1A3B20)
val surfaceContainerHighDark = Color(0xFF2E5B3D)
val surfaceContainerHighestDark = Color(0xFF3D6D50)

//val primaryDarkMediumContrast = Color(0xFFACCDFF)
//val onPrimaryDarkMediumContrast = Color(0xFF001731)
//val primaryContainerDarkMediumContrast = Color(0xFF6F92C5)
//val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
//val secondaryDarkMediumContrast = Color(0xFFC0CBE0)
//val onSecondaryDarkMediumContrast = Color(0xFF0C1726)
//val secondaryContainerDarkMediumContrast = Color(0xFF8691A4)
//val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
//val tertiaryDarkMediumContrast = Color(0xFFDEC1E7)
//val onTertiaryDarkMediumContrast = Color(0xFF210E2A)
//val tertiaryContainerDarkMediumContrast = Color(0xFFA288AB)
//val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
//val errorDarkMediumContrast = Color(0xFFFFBAB1)
//val onErrorDarkMediumContrast = Color(0xFF370001)
//val errorContainerDarkMediumContrast = Color(0xFFFF5449)
//val onErrorContainerDarkMediumContrast = Color(0xFF000000)
//val backgroundDarkMediumContrast = Color(0xFF111318)
//val onBackgroundDarkMediumContrast = Color(0xFFE1E2E9)
//val surfaceDarkMediumContrast = Color(0xFF111318)
//val onSurfaceDarkMediumContrast = Color(0xFFFBFAFF)
//val surfaceVariantDarkMediumContrast = Color(0xFF43474E)
//val onSurfaceVariantDarkMediumContrast = Color(0xFFC8CAD4)
//val outlineDarkMediumContrast = Color(0xFFA0A3AB)
//val outlineVariantDarkMediumContrast = Color(0xFF80838B)
//val scrimDarkMediumContrast = Color(0xFF000000)
//val inverseSurfaceDarkMediumContrast = Color(0xFFE1E2E9)
//val inverseOnSurfaceDarkMediumContrast = Color(0xFF282A2F)
//val inversePrimaryDarkMediumContrast = Color(0xFF224977)
//val surfaceDimDarkMediumContrast = Color(0xFF111318)
//val surfaceBrightDarkMediumContrast = Color(0xFF37393E)
//val surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0E13)
//val surfaceContainerLowDarkMediumContrast = Color(0xFF191C20)
//val surfaceContainerDarkMediumContrast = Color(0xFF1D2024)
//val surfaceContainerHighDarkMediumContrast = Color(0xFF282A2F)
//val surfaceContainerHighestDarkMediumContrast = Color(0xFF32353A)
//
//val primaryDarkHighContrast = Color(0xFFFBFAFF)
//val onPrimaryDarkHighContrast = Color(0xFF000000)
//val primaryContainerDarkHighContrast = Color(0xFFACCDFF)
//val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
//val secondaryDarkHighContrast = Color(0xFFFBFAFF)
//val onSecondaryDarkHighContrast = Color(0xFF000000)
//val secondaryContainerDarkHighContrast = Color(0xFFC0CBE0)
//val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
//val tertiaryDarkHighContrast = Color(0xFFFFF9FB)
//val onTertiaryDarkHighContrast = Color(0xFF000000)
//val tertiaryContainerDarkHighContrast = Color(0xFFDEC1E7)
//val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
//val errorDarkHighContrast = Color(0xFFFFF9F9)
//val onErrorDarkHighContrast = Color(0xFF000000)
//val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
//val onErrorContainerDarkHighContrast = Color(0xFF000000)
//val backgroundDarkHighContrast = Color(0xFF111318)
//val onBackgroundDarkHighContrast = Color(0xFFE1E2E9)
//val surfaceDarkHighContrast = Color(0xFF111318)
//val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
//val surfaceVariantDarkHighContrast = Color(0xFF43474E)
//val onSurfaceVariantDarkHighContrast = Color(0xFFFBFAFF)
//val outlineDarkHighContrast = Color(0xFFC8CAD4)
//val outlineVariantDarkHighContrast = Color(0xFFC8CAD4)
//val scrimDarkHighContrast = Color(0xFF000000)
//val inverseSurfaceDarkHighContrast = Color(0xFFE1E2E9)
//val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
//val inversePrimaryDarkHighContrast = Color(0xFF002A53)
//val surfaceDimDarkHighContrast = Color(0xFF111318)
//val surfaceBrightDarkHighContrast = Color(0xFF37393E)
//val surfaceContainerLowestDarkHighContrast = Color(0xFF0C0E13)
//val surfaceContainerLowDarkHighContrast = Color(0xFF191C20)
//val surfaceContainerDarkHighContrast = Color(0xFF1D2024)
//val surfaceContainerHighDarkHighContrast = Color(0xFF282A2F)
//val surfaceContainerHighestDarkHighContrast = Color(0xFF32353A)

val gold = Color(0xFFFFD700)
val silver = Color(0xFFC0C0C0)
val bronze = Color(0xFFCD7F32)
